In [2]:
import numpy as np

In [3]:
# Q1.Create a 3×3 numpy array of all True’s (Boolean)
np.full((3,3),True,dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [4]:
np.ones((3,3),bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [8]:
# Q2. Replace all odd numbers in array with -1
arr=np.array([1,3,4,9])

arr[arr%2==1]=-1
arr

array([-1, -1,  4, -1])

In [8]:
# Q3. Get the common items between array1 and array2

arr1=np.array([[1,1,2],[3,4,5]])
arr2=np.array([[2,1,5],[4,6,7]])

np.intersect1d(arr1,arr2)


array([1, 2, 4, 5])

In [10]:
# Q4.Get the positions where elements of a and b match
arr1=np.array([1,1,2,3,4,5])
arr2=np.array([2,1,5,4,6,7])
np.where(arr1==arr2)
np.where(arr1==(arr2-1))

(array([0, 3], dtype=int64),)

In [55]:
# Q5. Swap columns 1 and 2 in the array.
arr=np.arange(9).reshape(3,3)
arr


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [56]:
arr[:,[1,0,2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [30]:
# Q6.Swap rows 1 and 2 in the array.

arr[[1,0,2],:]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

In [36]:
# Q7.Reverse the columns of a 2D array.
arr[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [37]:
#  Q8. Reverse the rows of a 2D array.
arr[::]

In [51]:
# Q9. Print or show only 3 decimal places of the numpy array.
rand_arr=np.random.random([5,3])
print(rand_arr)

[[0.  0.3 1. ]
 [0.3 0.5 0.8]
 [0.9 0.  0.9]
 [0.4 0.4 0.6]
 [0.4 0.6 0.7]]


In [53]:
np.set_printoptions(precision=1)
rand_arr[:]

array([[0. , 0.3, 1. ],
       [0.3, 0.5, 0.8],
       [0.9, 0. , 0.9],
       [0.4, 0.4, 0.6],
       [0.4, 0.6, 0.7]])

In [57]:
# Q10. how to compute mean, median and standard deviation of an array.

mu,med,std=np.mean(arr),np.median(arr),np.std(arr)
print(mu,med,std)

4.0 4.0 2.581988897471611
