In [3]:
import numpy as np
x = np.array([1,2,3])
print(x)
print(type(x))
print(np.__version__) # numpy version
m = np.array([[4,5,6],[7,8,9]])
print(m)
print(m.ndim) # dimension of array


[1 2 3]
<class 'numpy.ndarray'>
1.19.2
[[4 5 6]
 [7 8 9]]
2


In [60]:
m.shape #no of rows and cols


(2, 3)

In [11]:
a = np.arange(0,30,2) #array in range
a
print(a)
a[-5::-2]


[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28]


array([20, 16, 12,  8,  4,  0])

In [12]:
a = a.reshape(3,5) #reshaping array
print(a)
print(a[2,2:5])  #row 2 and col in slice
print(a[a>15]) # greater than 15
a[a>15]=15 # assigned as 15
a

[[ 0  2  4  6  8]
 [10 12 14 16 18]
 [20 22 24 26 28]]
[[14 16 18]]
[16 18 20 22 24 26 28]


array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 15, 15],
       [15, 15, 15, 15, 15]])

In [63]:
o=np.linspace(0,4,12)
o

array([0.        , 0.36363636, 0.72727273, 1.09090909, 1.45454545,
       1.81818182, 2.18181818, 2.54545455, 2.90909091, 3.27272727,
       3.63636364, 4.        ])

In [64]:
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print('number of dimensions :', arr.ndim)


[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [65]:
o=o.reshape(2,6) #
o

array([[0.        , 0.36363636, 0.72727273, 1.09090909, 1.45454545,
        1.81818182],
       [2.18181818, 2.54545455, 2.90909091, 3.27272727, 3.63636364,
        4.        ]])

In [66]:
o.resize(3,4)
o

array([[0.        , 0.36363636, 0.72727273, 1.09090909],
       [1.45454545, 1.81818182, 2.18181818, 2.54545455],
       [2.90909091, 3.27272727, 3.63636364, 4.        ]])

In [67]:
np.ones((3,2)) #default float values 

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [68]:
np.ones((3,2),int) #int values of ones

array([[1, 1],
       [1, 1],
       [1, 1]])

In [69]:
np.zeros((2,3),int) #int values of zero

array([[0, 0, 0],
       [0, 0, 0]])

In [70]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [71]:
b=np.eye(3) #identity matrix
b

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
y=np.array([4,5,6]) #diagonal matrix
print(a)
np.diag(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[4 0 0]
 [0 5 0]
 [0 0 6]]


array([[4, 0, 0],
       [0, 5, 0],
       [0, 0, 6]])

In [18]:
np.array([5,2,3]*3) #repeat the entire array

array([5, 2, 3, 5, 2, 3, 5, 2, 3])

In [19]:
np.repeat([5,2,3],3) #repeatt every no 

array([5, 5, 5, 2, 2, 2, 3, 3, 3])

In [75]:
p=np.ones((2,3),int)
print(p)
t=np.ones([4,3],int)
print(t)

[[1 1 1]
 [1 1 1]]
[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]


In [76]:
np.vstack([2*p,t]) #no of cloumn should be same

array([[2, 2, 2],
       [2, 2, 2],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [77]:
np.hstack([p,2*p]) #no of rows need to be same

array([[1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2]])

In [20]:
m = np.array([[4,5,6],[7,8,9]])
m

array([[4, 5, 6],
       [7, 8, 9]])

In [21]:
m.T #transpose

array([[4, 7],
       [5, 8],
       [6, 9]])

In [80]:
m.dtype #type of array

dtype('int32')

In [81]:
m =m.astype('f') #changing type of array
m

array([[4., 5., 6.],
       [7., 8., 9.]], dtype=float32)

In [82]:
#Qn 1
arr = np.ones((3,3),bool)
print(arr)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [83]:
#Qn 2
a = np.array([2,5,6,7,8,4,3])
a[a%2!=0] = -1
a

array([ 2, -1,  6, -1,  8,  4, -1])

In [84]:
#Qn 3
a = np.array([1,2,3,4,5])
b = np.array([2,4,6,8,10])
np.intersect1d(a, b)

array([2, 4])

In [85]:
np.where(a==b)

(array([], dtype=int64),)